info:
  app:
    name: Circuit Breaker
    description: Hystix - Circuit Breaker - Fault tolerance

    
management:
  security: 
    enabled: false

server:
  port: 6161

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8761}/eureka/

---
spring:
  profiles: docker
 
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
