server:
  port: ${PORT:8761}

    
management:
  security: 
    enabled: false

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

---

spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/  
